export const languageConfigs = [
  {
    code: "ta",
    name: "Tamil",
    nativeName: "தமிழ்",
    flag: "🇮🇳",
    tmdbCode: "ta-IN",
    region: "IN",
    genres: [
      {
        id: "28",
        name: "அதிரடி",
        icon: "💥",
        color: "text-red-400",
        description: "Action-packed Tamil blockbusters with stunning stunts",
      },
      {
        id: "35",
        name: "நகைச்சுவை",
        icon: "😂",
        color: "text-yellow-400",
        description: "Hilarious Tamil comedies that will make you laugh",
      },
      {
        id: "18",
        name: "நாடகம்",
        icon: "🎭",
        color: "text-purple-400",
        description: "Emotional Tamil dramas with powerful storytelling",
      },
      {
        id: "10749",
        name: "காதல்",
        icon: "💕",
        color: "text-pink-400",
        description: "Beautiful Tamil romantic movies",
      },
      {
        id: "53",
        name: "த்ரில்லர்",
        icon: "🔥",
        color: "text-orange-400",
        description: "Edge-of-your-seat Tamil thrillers",
      },
      {
        id: "27",
        name: "திகில்",
        icon: "👻",
        color: "text-gray-400",
        description: "Spine-chilling Tamil horror movies",
      },
      {
        id: "878",
        name: "அறிவியல் புனைகதை",
        icon: "🚀",
        color: "text-blue-400",
        description: "Futuristic Tamil sci-fi adventures",
      },
      {
        id: "14",
        name: "கற்பனை",
        icon: "🧙‍♂️",
        color: "text-green-400",
        description: "Magical Tamil fantasy worlds",
      },
    ],
    texts: {
      welcome: "தமிழ் சினிமாவுக்கு வரவேற்கிறோம்",
      selectGenre: "உங்கள் விருப்பமான வகையைத் தேர்ந்தெடுக்கவும்",
      popularIn: "தமிழில் பிரபலமான",
      backToLanguages: "மொழிகளுக்குத் திரும்பு",
      searchIn: "தேடுங்கள்",
      noMoviesFound: "திரைப்படங்கள் கிடைக்கவில்லை",
      loadingMovies: "திரைப்படங்களை ஏற்றுகிறது...",
      watchNow: "இப்போது பார்க்கவும்",
      year: "ஆண்டு",
      rating: "மதிப்பீடு",
      votes: "வாக்குகள்",
    },
  },
  {
    code: "te",
    name: "Telugu",
    nativeName: "తెలుగు",
    flag: "🇮🇳",
    tmdbCode: "te-IN",
    region: "IN",
    genres: [
      {
        id: "28",
        name: "యాక్షన్",
        icon: "⚡",
        color: "text-red-400",
        description: "High-octane Telugu action entertainers",
      },
      {
        id: "35",
        name: "కామెడీ",
        icon: "🤣",
        color: "text-yellow-400",
        description: "Laugh-out-loud Telugu comedies",
      },
      {
        id: "18",
        name: "డ్రామా",
        icon: "🎬",
        color: "text-purple-400",
        description: "Heart-touching Telugu family dramas",
      },
      {
        id: "10749",
        name: "రొమాన్స్",
        icon: "💖",
        color: "text-pink-400",
        description: "Beautiful Telugu love stories",
      },
      {
        id: "53",
        name: "థ్రిల్లర్",
        icon: "🔪",
        color: "text-orange-400",
        description: "Gripping Telugu suspense thrillers",
      },
      {
        id: "27",
        name: "భయానక",
        icon: "😱",
        color: "text-gray-400",
        description: "Terrifying Telugu horror films",
      },
      {
        id: "878",
        name: "సైన్స్ ఫిక్షన్",
        icon: "🛸",
        color: "text-blue-400",
        description: "Innovative Telugu sci-fi movies",
      },
      {
        id: "14",
        name: "ఫాంటసీ",
        icon: "🐉",
        color: "text-green-400",
        description: "Mythological Telugu fantasy epics",
      },
    ],
    texts: {
      welcome: "తెలుగు సినిమాకు స్వాగతం",
      selectGenre: "మీ ఇష్టమైన జానర్‌ను ఎంచుకోండి",
      popularIn: "తెలుగులో ప్రసిద్ధమైన",
      backToLanguages: "భాషలకు తిరిగి వెళ్లండి",
      searchIn: "వెతకండి",
      noMoviesFound: "సినిమాలు దొరకలేదు",
      loadingMovies: "సినిమాలను లోడ్ చేస్తోంది...",
      watchNow: "ఇప్పుడు చూడండి",
      year: "సంవత్సరం",
      rating: "రేటింగ్",
      votes: "వోట్లు",
    },
  },
  {
    code: "hi",
    name: "Hindi",
    nativeName: "हिंदी",
    flag: "🇮🇳",
    tmdbCode: "hi-IN",
    region: "IN",
    genres: [
      {
        id: "28",
        name: "एक्शन",
        icon: "💪",
        color: "text-red-400",
        description: "Bollywood action blockbusters with amazing stunts",
      },
      {
        id: "35",
        name: "कॉमेडी",
        icon: "😄",
        color: "text-yellow-400",
        description: "Hilarious Bollywood comedy entertainers",
      },
      {
        id: "18",
        name: "ड्रामा",
        icon: "🎪",
        color: "text-purple-400",
        description: "Emotional Bollywood family dramas",
      },
      {
        id: "10749",
        name: "रोमांस",
        icon: "💝",
        color: "text-pink-400",
        description: "Classic Bollywood romantic movies",
      },
      {
        id: "53",
        name: "थ्रिलर",
        icon: "🎯",
        color: "text-orange-400",
        description: "Suspenseful Hindi thriller movies",
      },
      {
        id: "27",
        name: "हॉरर",
        icon: "🧟",
        color: "text-gray-400",
        description: "Scary Hindi horror films",
      },
      {
        id: "878",
        name: "साइंस फिक्शन",
        icon: "🌌",
        color: "text-blue-400",
        description: "Futuristic Hindi sci-fi adventures",
      },
      {
        id: "14",
        name: "फैंटेसी",
        icon: "🧞‍♂️",
        color: "text-green-400",
        description: "Magical Hindi fantasy tales",
      },
    ],
    texts: {
      welcome: "हिंदी सिनेमा में आपका स्वागत है",
      selectGenre: "अपनी पसंदीदा शैली चुनें",
      popularIn: "हिंदी में लोकप्रिय",
      backToLanguages: "भाषाओं पर वापस जाएं",
      searchIn: "खोजें",
      noMoviesFound: "कोई फिल्म नहीं मिली",
      loadingMovies: "फिल्में लोड हो रही हैं...",
      watchNow: "अभी देखें",
      year: "साल",
      rating: "रेटिंग",
      votes: "वोट",
    },
  },
  {
    code: "en",
    name: "English",
    nativeName: "English",
    flag: "🇺🇸",
    tmdbCode: "en-US",
    region: "US",
    genres: [
      {
        id: "28",
        name: "Action",
        icon: "🎬",
        color: "text-red-400",
        description: "High-octane Hollywood action blockbusters",
      },
      {
        id: "35",
        name: "Comedy",
        icon: "🎭",
        color: "text-yellow-400",
        description: "Hilarious Hollywood comedies",
      },
      {
        id: "18",
        name: "Drama",
        icon: "🏆",
        color: "text-purple-400",
        description: "Award-winning Hollywood dramas",
      },
      {
        id: "10749",
        name: "Romance",
        icon: "💕",
        color: "text-pink-400",
        description: "Beautiful Hollywood romantic movies",
      },
      {
        id: "53",
        name: "Thriller",
        icon: "🔥",
        color: "text-orange-400",
        description: "Edge-of-your-seat Hollywood thrillers",
      },
      {
        id: "27",
        name: "Horror",
        icon: "👻",
        color: "text-gray-400",
        description: "Spine-chilling Hollywood horror",
      },
      {
        id: "878",
        name: "Sci-Fi",
        icon: "🚀",
        color: "text-blue-400",
        description: "Mind-bending Hollywood sci-fi",
      },
      {
        id: "14",
        name: "Fantasy",
        icon: "🧙‍♂️",
        color: "text-green-400",
        description: "Magical Hollywood fantasy worlds",
      },
    ],
    texts: {
      welcome: "Welcome to English Cinema",
      selectGenre: "Choose your favorite genre",
      popularIn: "Popular in English",
      backToLanguages: "Back to Languages",
      searchIn: "Search in",
      noMoviesFound: "No movies found",
      loadingMovies: "Loading movies...",
      watchNow: "Watch Now",
      year: "Year",
      rating: "Rating",
      votes: "Votes",
    },
  },
  {
    code: "ml",
    name: "Malayalam",
    nativeName: "മലയാളം",
    flag: "🇮🇳",
    tmdbCode: "ml-IN",
    region: "IN",
    genres: [
      {
        id: "28",
        name: "ആക്ഷൻ",
        icon: "⚔️",
        color: "text-red-400",
        description: "Thrilling Malayalam action movies",
      },
      {
        id: "35",
        name: "കോമഡി",
        icon: "😆",
        color: "text-yellow-400",
        description: "Entertaining Malayalam comedies",
      },
      {
        id: "18",
        name: "ഡ്രാമ",
        icon: "🎨",
        color: "text-purple-400",
        description: "Artistic Malayalam dramas",
      },
      {
        id: "10749",
        name: "പ്രണയം",
        icon: "💞",
        color: "text-pink-400",
        description: "Beautiful Malayalam love stories",
      },
      {
        id: "53",
        name: "ത്രില്ലർ",
        icon: "🗡️",
        color: "text-orange-400",
        description: "Gripping Malayalam thrillers",
      },
      {
        id: "27",
        name: "ഹൊറർ",
        icon: "💀",
        color: "text-gray-400",
        description: "Scary Malayalam horror films",
      },
      {
        id: "878",
        name: "സയൻസ് ഫിക്ഷൻ",
        icon: "🛰️",
        color: "text-blue-400",
        description: "Innovative Malayalam sci-fi",
      },
      {
        id: "14",
        name: "ഫാന്റസി",
        icon: "🌟",
        color: "text-green-400",
        description: "Magical Malayalam fantasy",
      },
    ],
    texts: {
      welcome: "മലയാളം സിനിമയിലേക്ക് സ്വാഗതം",
      selectGenre: "നിങ്ങളുടെ ഇഷ്ടമുള്ള വിഭാഗം തിരഞ്ഞെടുക്കുക",
      popularIn: "മലയാളത്തിൽ ജനപ്രിയമായത്",
      backToLanguages: "ഭാഷകളിലേക്ക് മടങ്ങുക",
      searchIn: "തിരയുക",
      noMoviesFound: "സിനിമകൾ കണ്ടെത്തിയില്ല",
      loadingMovies: "സിനിമകൾ ലോഡ് ചെയ്യുന്നു...",
      watchNow: "ഇപ്പോൾ കാണുക",
      year: "വർഷം",
      rating: "റേറ്റിംഗ്",
      votes: "വോട്ടുകൾ",
    },
  },
]
