export const englishTexts = {
  appName: "MOVIEFLIX",
  welcome: "Welcome to the Cinema",
  welcomeBack: "Welcome Back!",
  joinCinema: "Join the Experience",
  enterCinema: "ENTER CINEMA",
  joinMovieFlix: "JOIN MOVIEFLIX",
  enteringCinema: "ENTERING CINEMA...",
  fullName: "Full Name",
  emailAddress: "Email Address",
  password: "Password",
  newToMovieFlix: "New to MovieFlix? Join Now",
  alreadyMember: "Already a member? Sign In",
  premiumExperience: "Premium Experience",
  welcomeBackUser: "Welcome back, {name}!",
  exitCinema: "EXIT CINEMA",
  searchPlaceholder: "Search for blockbusters, classics, or hidden gems...",
  searchResults: "Search Results",
  featuredInCinema: "Featured in Cinema",
  premiumMovies: "Premium Movies",
  cinemaQuality: "Cinema Quality",
  alwaysOpen: "Always Open",
  watchNow: "WATCH NOW",
  poweredBy: "Powered by",
  searchFailed: "Failed to search movies. Please try again.",
  enterMovieTitle: "Please enter a movie title",
  searchingArchives: "Searching the cinema archives...",
  genres: {
    action: "Action",
    thriller: "Thriller",
    sciFi: "Sci-Fi",
    horror: "Horror",
    comedy: "Comedy",
    drama: "Drama",
    marvel: "Marvel",
    dc: "DC",
  },
}
