export const hindiTexts = {
  appName: "मूवीफ्लिक्स",
  welcome: "सिनेमा में आपका स्वागत है",
  welcomeBack: "वापस स्वागत है!",
  joinCinema: "अनुभव में शामिल हों",
  enterCinema: "सिनेमा में प्रवेश करें",
  joinMovieFlix: "मूवीफ्लिक्स में शामिल हों",
  enteringCinema: "सिनेमा में प्रवेश कर रहे हैं...",
  fullName: "पूरा नाम",
  emailAddress: "ईमेल पता",
  password: "पासवर्ड",
  newToMovieFlix: "मूवीफ्लिक्स में नए हैं? अभी शामिल हों",
  alreadyMember: "पहले से सदस्य हैं? साइन इन करें",
  premiumExperience: "प्रीमियम अनुभव",
  welcomeBackUser: "वापस स्वागत है, {name}!",
  exitCinema: "सिनेमा से बाहर निकलें",
  searchPlaceholder: "ब्लॉकबस्टर, क्लासिक्स या छुपे हुए रत्न खोजें...",
  searchResults: "खोज परिणाम",
  featuredInCinema: "सिनेमा में विशेष",
  premiumMovies: "प्रीमियम फिल्में",
  cinemaQuality: "सिनेमा गुणवत्ता",
  alwaysOpen: "हमेशा खुला",
  watchNow: "अभी देखें",
  poweredBy: "द्वारा संचालित",
  searchFailed: "फिल्में खोजने में असफल। कृपया पुनः प्रयास करें।",
  enterMovieTitle: "कृपया फिल्म का शीर्षक दर्ज करें",
  searchingArchives: "सिनेमा अभिलेखागार खोज रहे हैं...",
  genres: {
    action: "एक्शन",
    thriller: "थ्रिलर",
    sciFi: "साइंस फिक्शन",
    horror: "हॉरर",
    comedy: "कॉमेडी",
    drama: "ड्रामा",
    marvel: "मार्वल",
    dc: "डीसी",
  },
}
