export const tamilTexts = {
  appName: "மூவிஃப்ளிக்ஸ்",
  welcome: "சினிமாவுக்கு வரவேற்கிறோம்",
  welcomeBack: "மீண்டும் வரவேற்கிறோம்!",
  joinCinema: "அனுபவத்தில் சேருங்கள்",
  enterCinema: "சினிமாவில் நுழையுங்கள்",
  joinMovieFlix: "மூவிஃப்ளிக்ஸில் சேருங்கள்",
  enteringCinema: "சினிமாவில் நுழைகிறது...",
  fullName: "முழு பெயர்",
  emailAddress: "மின்னஞ்சல் முகவரி",
  password: "கடவுச்சொல்",
  newToMovieFlix: "மூவிஃப்ளிக்ஸில் புதியவரா? இப்போது சேருங்கள்",
  alreadyMember: "ஏற்கனவே உறுப்பினரா? உள்நுழையுங்கள்",
  premiumExperience: "பிரீமியம் அனுபவம்",
  welcomeBackUser: "மீண்டும் வரவேற்கிறோம், {name}!",
  exitCinema: "சினிமாவிலிருந்து வெளியேறு",
  searchPlaceholder: "பிளாக்பஸ்டர்கள், கிளாசிக்ஸ் அல்லது மறைக்கப்பட்ட ரத்தினங்களைத் தேடுங்கள்...",
  searchResults: "தேடல் முடிவுகள்",
  featuredInCinema: "சினிமாவில் சிறப்பு",
  premiumMovies: "பிரீமியம் திரைப்படங்கள்",
  cinemaQuality: "சினிமா தரம்",
  alwaysOpen: "எப்போதும் திறந்திருக்கும்",
  watchNow: "இப்போது பார்க்கவும்",
  poweredBy: "இதனால் இயக்கப்படுகிறது",
  searchFailed: "திரைப்படங்களைத் தேடுவதில் தோல்வி. மீண்டும் முயற்சிக்கவும்.",
  enterMovieTitle: "தயவுசெய்து திரைப்படத்தின் தலைப்பை உள்ளிடவும்",
  searchingArchives: "சினிமா காப்பகங்களைத் தேடுகிறது...",
  genres: {
    action: "அதிரடி",
    thriller: "த்ரில்லர்",
    sciFi: "அறிவியல் புனைகதை",
    horror: "திகில்",
    comedy: "நகைச்சுவை",
    drama: "நாடகம்",
    marvel: "மார்வெல்",
    dc: "டிசி",
  },
}
