export const teluguTexts = {
  appName: "మూవీఫ్లిక్స్",
  welcome: "సినిమాకు స్వాగతం",
  welcomeBack: "తిరిగి స్వాగతం!",
  joinCinema: "అనుభవంలో చేరండి",
  enterCinema: "సినిమాలో ప్రవేశించండి",
  joinMovieFlix: "మూవీఫ్లిక్స్‌లో చేరండి",
  enteringCinema: "సినిమాలో ప్రవేశిస్తోంది...",
  fullName: "పూర్తి పేరు",
  emailAddress: "ఇమెయిల్ చిరునామా",
  password: "పాస్‌వర్డ్",
  newToMovieFlix: "మూవీఫ్లిక్స్‌కు కొత్తవారా? ఇప్పుడే చేరండి",
  alreadyMember: "ఇప్పటికే సభ్యుడా? సైన్ ఇన్ చేయండి",
  premiumExperience: "ప్రీమియం అనుభవం",
  welcomeBackUser: "తిరిగి స్వాగతం, {name}!",
  exitCinema: "సినిమా నుండి నిష్క్రమించండి",
  searchPlaceholder: "బ్లాక్‌బస్టర్లు, క్లాసిక్‌లు లేదా దాచిన రత్నాలను వెతకండి...",
  searchResults: "శోధన ఫలితాలు",
  featuredInCinema: "సినిమాలో ప్రత్యేకం",
  premiumMovies: "ప్రీమియం సినిమాలు",
  cinemaQuality: "సినిమా నాణ్యత",
  alwaysOpen: "ఎల్లప్పుడూ తెరిచి ఉంటుంది",
  watchNow: "ఇప్పుడు చూడండి",
  poweredBy: "దీని ద్వారా శక్తిని పొందింది",
  searchFailed: "సినిమాలను వెతకడంలో విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.",
  enterMovieTitle: "దయచేసి సినిమా టైటిల్‌ను నమోదు చేయండి",
  searchingArchives: "సినిమా ఆర్కైవ్‌లను వెతుకుతోంది...",
  genres: {
    action: "యాక్షన్",
    thriller: "థ్రిల్లర్",
    sciFi: "సైన్స్ ఫిక్షన్",
    horror: "భయానక",
    comedy: "కామెడీ",
    drama: "డ్రామా",
    marvel: "మార్వెల్",
    dc: "డిసి",
  },
}
